version: 2

sources:
  - name: demo
    database: demo
    schema: demo_schema
    tables:
      - name: bike
      - name: weather

  - name: uscrime
    database: US_CRIME
    schema: CYBERSYN
    tables:
      - name: URBAN_CRIME_INCIDENT_LOG